version: '3.8'

services:
  frontend:
    build:
      context: ./vue
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_APP_URL: ${VITE_APP_URL}
        VITE_SHARE_URL: ${VITE_SHARE_URL}
    ports:
      - "3000:80"
    networks:
      - openticon_network
networks:
  openticon_network:
    external: true
